/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-ignore
import "./globals.css";

import { excalifont } from "@/fonts/excalifont";

import type { Metadata } from "next";
import MainLayout from "./../components/ui/root/main-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${excalifont.className} antialiased bg-black h-screen w-screen`}
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
