/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-ignore
import "./globals.css";

import { excalifont } from "@/fonts/excalifont";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${excalifont.className} antialiased`}>{children}</body>
    </html>
  );
}
